name: Lint

on: push

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64

      - name: Checkout
        uses: actions/checkout@master

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run flake8
        run: flake8 Basic_Python_Diploma
